package main

import (
	"context"
	_ "embed"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/baskararestu/dataporter/api"
	"github.com/baskararestu/dataporter/config"
	"github.com/baskararestu/dataporter/database"
	_ "github.com/baskararestu/dataporter/docs" // generated by swag init
	applogger "github.com/baskararestu/dataporter/logger"
	"github.com/baskararestu/dataporter/migration"
	"github.com/baskararestu/dataporter/monitoring"
	"github.com/baskararestu/dataporter/repository"
	"github.com/baskararestu/dataporter/server"
	"github.com/joho/godotenv"
	"github.com/rs/zerolog/log"
)

//go:embed scripts/001_init_emr.sql
var emrDDL string

//go:embed scripts/002_init_simrs.sql
var simrsDDL string

// @title           DataPorter API
// @version         1.0
// @description     REST API for migrating patient records from EMR PostgreSQL to SIMRS with schema transformation.
// @contact.name    Baskara Restu
// @license.name    MIT
// @host            localhost:8080
// @BasePath        /
func main() {
	// Load .env if present (local dev). In production, env vars are injected directly.
	_ = godotenv.Load()

	cfg, err := config.Load()
	if err != nil {
		fmt.Fprintf(os.Stderr, "config error: %v\n", err)
		os.Exit(1)
	}

	applogger.Setup(cfg.LogLevel)

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT)
	defer stop()

	// Bootstrap: create databases if missing, apply schemas, seed EMR data.
	// Fully idempotent — safe on every startup.
	if err := database.Bootstrap(ctx, cfg, emrDDL, simrsDDL); err != nil {
		log.Fatal().Err(err).Msg("database bootstrap failed")
	}

	db, err := database.Connect(ctx, cfg.Source.DSN(), cfg.Target.DSN())
	if err != nil {
		log.Fatal().Err(err).Msg("database connection failed")
	}
	defer db.Close(ctx)

	jobRepo := repository.NewJobRepository(db.Target)
	tracker := monitoring.NewTracker()
	migrator := migration.NewMigrator(db.Source, db.Target, jobRepo, tracker)

	handler := api.NewHandler(ctx, jobRepo, migrator, tracker, db.Source, db.Target)
	mux := api.NewRouter(handler)

	srv := server.New(cfg.HTTPPort, mux)
	if err := srv.Run(ctx, cfg.HTTPPort); err != nil {
		log.Error().Err(err).Msg("server shutdown error")
	}
}
